name: Trigger auto deployment for container-app-pn4uukgyjkqao

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-pn4uukgyjkqao-AutoDeployTrigger-21ad8abc-dfba-4b23-97e3-7e048ae9aac8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPN4UUKGYJKQAO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPN4UUKGYJKQAO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPN4UUKGYJKQAO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPPN4UUKGYJKQAO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPN4UUKGYJKQAO_REGISTRY_PASSWORD }}
          containerAppName: container-app-pn4uukgyjkqao
          resourceGroup: appspacesragappabcc8867
          imageToBuild: default/container-app-pn4uukgyjkqao:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


